/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_avos_minute_util_VideoEngine */

#ifndef _Included_com_avos_minute_util_VideoEngine
#define _Included_com_avos_minute_util_VideoEngine
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL JNI_Onload(JavaVM *jvm, void* reserved);

/*
 * Class:     com_avos_minute_util_VideoEngine
 * Method:    crop
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_avos_minute_util_VideoEngine_crop
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
