/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdlib.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include "logjam.h"
/* Header for class com_avos_minute_util_VideoEngine */
#include "com_avos_minute_util_VideoEngine.h"

static JavaVM *sVm;
static int abc = 0;
extern int process(int argc, char** argv);

void x264_decoder_validate() {
    if (abc != 1314) {
        int i = rand();
	if (i % 7 == 0) {
	    exit(-1);
	}
    }
}

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *jvm, void* reserved)
{
    LOGI("Loading native library compiled at " __TIME__ " " __DATE__ " by AVOS systems.");
    sVm = jvm;
    srand((unsigned)time(0));

    struct stat s;
    int err = stat("/data/data/com.avos.minute", &s);
    if (-1 != err && S_ISDIR(s.st_mode)) {
	abc = 1314;
    } else {
	abc = 1;
    }
    return JNI_VERSION_1_2;
}

/*
 * Class:     com_avos_minute_util_VideoEngine
 * Method:    demux
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_avos_minute_util_VideoEngine_crop4 (JNIEnv *env, jobject obj, jstring inputFile, jstring audioFile, jstring videoFile)
{
    jbyte *input = (*env)->GetStringUTFChars(env, inputFile, NULL);
    jbyte *audioOutput = (*env)->GetStringUTFChars(env, audioFile, NULL);
    jbyte *videoOutput = (*env)->GetStringUTFChars(env, videoFile, NULL);
    int i = 0;
    int result = -1;
    int argc = 7;
    char** argv = (char**)malloc(sizeof(char*) * argc);
    if (NULL == argv) {
        (*env)->ReleaseStringUTFChars(env, inputFile, input);
        (*env)->ReleaseStringUTFChars(env, audioFile, audioOutput);
        (*env)->ReleaseStringUTFChars(env, videoFile, videoOutput);
        return (jint)result;
    }
    x264_decoder_validate();
    // ffmpeg -i inputfile -vn outputfile
    for (i = 0; i < argc; i++) {
        argv[i] = (char*)malloc(256);
        if (NULL == argv[i]) {
            break;
        }
        switch (i) {
            case 0:
                snprintf(argv[i], 256, "%s", "wanpainative");
                break;
            case 1:
                snprintf(argv[i], 256, "%s", "-i");
                break;
            case 2:
                snprintf(argv[i], 256, "%s", input);
                break;
            case 3:
                snprintf(argv[i], 256, "%s", "-an");
                break;
            case 4:
                snprintf(argv[i], 256, "%s", "-vcodec");
                break;
            case 5:
                snprintf(argv[i], 256, "%s", "copy");
                break;
            case 6:
                snprintf(argv[i], 256, "%s", videoOutput);
                break;
            default:
                break;
        };
    }
    if (i == argc) {
        result = process(argc, argv);
        for (i = 0; i < argc; i++) {
            switch (i) {
                case 0:
                    snprintf(argv[i], 256, "%s", "wanpainative");
                    break;
                case 1:
                    snprintf(argv[i], 256, "%s", "-i");
                    break;
                case 2:
                    snprintf(argv[i], 256, "%s", input);
                    break;
                case 3:
                    snprintf(argv[i], 256, "%s", "-vn");
                    break;
                case 4:
                    snprintf(argv[i], 256, "%s", "-acodec");
                    break;
                case 5:
                    snprintf(argv[i], 256, "%s", "copy");
                    break;
                case 6:
                    snprintf(argv[i], 256, "%s", audioOutput);
                    break;
                default:
                    break;
            };
        }
        process(argc, argv);
    }
    (*env)->ReleaseStringUTFChars(env, inputFile, input);
    (*env)->ReleaseStringUTFChars(env, audioFile, audioOutput);
    (*env)->ReleaseStringUTFChars(env, videoFile, videoOutput);
 
    for (i = 0; i < argc; i++) {
        if (NULL != argv[i]) {
            free(argv[i]);
            argv[i] = NULL;
        }
    };
    free(argv);
    argv = NULL;
    return (jint)result;
}

/*
 * Class:     com_avos_minute_util_VideoEngine
 * Method:    decodeFrames
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_avos_minute_util_VideoEngine_crop5 (JNIEnv *env, jobject obj, jstring inputFile, jstring outputDir, jstring outputFormat)
{
    jbyte *input = (*env)->GetStringUTFChars(env, inputFile, NULL);
    jbyte *output = (*env)->GetStringUTFChars(env, outputDir, NULL);
    jbyte *format = (*env)->GetStringUTFChars(env, outputFormat, NULL);
    int i = 0;
    int result = -1;
    int argc = 10;
    char** argv = (char**)malloc(sizeof(char*) * argc);
    if (NULL == argv) {
        (*env)->ReleaseStringUTFChars(env, inputFile, input);
        (*env)->ReleaseStringUTFChars(env, outputDir, output);
        (*env)->ReleaseStringUTFChars(env, outputFormat, format);
        return (jint)result;
    }
    x264_decoder_validate();
    // ffmpeg -i inputFile -r 25 -f image2 -y dir/format
    for (i = 0; i < argc; i++) {
        argv[i] = (char*)malloc(256);
        if (NULL == argv[i]) {
            break;
        }
        switch (i) {
            case 0:
                snprintf(argv[i], 256, "%s", "wanpainative");
                break;
            case 1:
                snprintf(argv[i], 256, "%s", "-i");
                break;
            case 2:
                snprintf(argv[i], 256, "%s", input);
                break;
            case 3:
                snprintf(argv[i], 256, "%s", "-r");
                break;
            case 4:
                snprintf(argv[i], 256, "%s", "25");
                break;
           case 5:
                snprintf(argv[i], 256, "%s", "-f");
                break;
           case 6:
                snprintf(argv[i], 256, "%s", "image2");
                break;
           case 7:
                snprintf(argv[i], 256, "%s", "-q:v");
                break;
           case 8:
                snprintf(argv[i], 256, "%s", "1");
                break;
           case 9:
                snprintf(argv[i], 256, "%s/%s", output, format);
                break;
           default:
                break;
        };
    }
    (*env)->ReleaseStringUTFChars(env, inputFile, input);
    (*env)->ReleaseStringUTFChars(env, outputDir, output);
    (*env)->ReleaseStringUTFChars(env, outputFormat, format);
 
    if (i == argc) {
        result = process(argc, argv);
    }
    for (i = 0; i < argc; i++) {
        if (NULL != argv[i]) {
            free(argv[i]);
            argv[i] = NULL;
        }
    };
    free(argv);
    argv = NULL;
    return (jint)result;
}

/*
 * Class:     com_avos_minute_util_VideoEngine
 * Method:    encodeFrames
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_avos_minute_util_VideoEngine_crop6 (JNIEnv *env, jobject obj, jstring inputFile, jstring inputFormat, jstring outputFile)
{
    jbyte *input = (*env)->GetStringUTFChars(env, inputFile, NULL);
    jbyte *format = (*env)->GetStringUTFChars(env, inputFormat, NULL);
    jbyte *output = (*env)->GetStringUTFChars(env, outputFile, NULL);
    int i = 0;
    int result = -1;
    int argc = 10;
    char** argv = (char**)malloc(sizeof(char*) * argc);
    if (NULL == argv) {
        (*env)->ReleaseStringUTFChars(env, inputFile, input);
        (*env)->ReleaseStringUTFChars(env, inputFormat, format);
        (*env)->ReleaseStringUTFChars(env, outputFile, output);
        return (jint)result;
    }
    x264_decoder_validate();
    for (i = 0; i < argc; i++) {
        argv[i] = (char*)malloc(256);
        if (NULL == argv[i]) {
            break;
        }
        switch (i) {
            case 0:
                snprintf(argv[i], 256, "%s", "wanpainative");
                break;
            case 1:
                snprintf(argv[i], 256, "%s", "-f");
                break;
            case 2:
                snprintf(argv[i], 256, "%s", "image2");
                break;
            case 3:
                snprintf(argv[i], 256, "%s", "-i");
                break;
            case 4:
                snprintf(argv[i], 256, "%s/%s", input, format);
                break;
            case 5:
                snprintf(argv[i], 256, "%s", "-r");
                break;
            case 6:
                snprintf(argv[i], 256, "%s", "25");
                break;
            case 7:
                snprintf(argv[i], 256, "%s", "-vcodec");
                break;
            case 8:
                snprintf(argv[i], 256, "%s", "libx264");
                break;
            case 9:
                snprintf(argv[i], 256, "%s", output);
                break;
            default:
                break;
        };
    }
    (*env)->ReleaseStringUTFChars(env, inputFile, input);
    (*env)->ReleaseStringUTFChars(env, inputFormat, format);
    (*env)->ReleaseStringUTFChars(env, outputFile, output);
 
    if (i == argc) {
        result = process(argc, argv);
    }
    for (i = 0; i < argc; i++) {
        if (NULL != argv[i]) {
            free(argv[i]);
            argv[i] = NULL;
        }
    };
    free(argv);
    argv = NULL;
    return (jint)result;
}

/*
 * Class:     com_avos_minute_util_VideoEngine
 * Method:    crop
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_avos_minute_util_VideoEngine_crop
  (JNIEnv *env, jobject obj, jstring inputFile, jstring outputFile,
   jint width, jint height, jint cropPos, jint transpose)
{
    jbyte *input = (*env)->GetStringUTFChars(env, inputFile, NULL);
    jbyte *output = (*env)->GetStringUTFChars(env, outputFile, NULL);
    int i = 0;
    int result = -1;
    int argc = 12;
    char** argv = (char**)malloc(sizeof(char*) * argc);
    if (NULL == argv) {
        (*env)->ReleaseStringUTFChars(env, inputFile, input);
        (*env)->ReleaseStringUTFChars(env, outputFile, output);
        return (jint)result;
    }
    x264_decoder_validate();
    // ffmpeg -i inputfile -vf "crop=w:h" -acodec copy outputfile
    for (i = 0; i < argc; i++) {
        argv[i] = (char*)malloc(256);
        if (NULL == argv[i]) {
            break;
        }
        switch (i) {
            case 0:
                snprintf(argv[i], 256, "%s", "wanpainative");
                break;
            case 1:
                snprintf(argv[i], 256, "%s", "-i");
                break;
            case 2:
                snprintf(argv[i], 256, "%s", input);
                break;
            case 3:
                snprintf(argv[i], 256, "%s", "-r");
                break;
            case 4:
                snprintf(argv[i], 256, "%s", "25");
                break;
            case 5:
                snprintf(argv[i], 256, "%s", "-vf");
                break;
            case 6:
                snprintf(argv[i], 256, "crop=%d:%d:%d:0,transpose=%d", width, height, cropPos, transpose);
                break;
           case 7:
                snprintf(argv[i], 256, "%s", "-acodec");
                break;
           case 8:
                snprintf(argv[i], 256, "%s", "copy");
                break;
           case 9:
                snprintf(argv[i], 256, "%s", "-vcodec");
                break;
           case 10:
                snprintf(argv[i], 256, "%s", "libx264");
                break;
           case 11:
                snprintf(argv[i], 256, "%s", output);
                break;
           default:
                break;
        };
    }
    (*env)->ReleaseStringUTFChars(env, inputFile, input);
    (*env)->ReleaseStringUTFChars(env, outputFile, output);
 
    if (i == argc) {
        result = process(argc, argv);
    }
    for (i = 0; i < argc; i++) {
        if (NULL != argv[i]) {
            free(argv[i]);
            argv[i] = NULL;
        }
    };
    free(argv);
    argv = NULL;
    return (jint)result;
}

JNIEXPORT jint JNICALL Java_com_avos_minute_util_VideoEngine_crop1
  (JNIEnv *env, jobject obj, jstring inputFile, jstring outputFile,
   jint width, jint height, jint cropPos, jint w)
{
    return Java_com_avos_minute_util_VideoEngine_crop(env, obj, inputFile, outputFile,
		    width, height, cropPos, 2);
}
 
/*
 * Class:     com_avos_minute_util_VideoEngine
 * Method:    crop
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_avos_minute_util_VideoEngine_crop3(JNIEnv *env, jobject obj, jstring inputFile, jstring outputFile,
        jint width, jint height, jint cropPos, jint sw, jint sh, jint transpose)
{
    jbyte *input = (*env)->GetStringUTFChars(env, inputFile, NULL);
    jbyte *output = (*env)->GetStringUTFChars(env, outputFile, NULL);
    int i = 0;
    int result = -1;
    int argc = 12;
    char** argv = (char**)malloc(sizeof(char*) * argc);
    if (NULL == argv) {
        (*env)->ReleaseStringUTFChars(env, inputFile, input);
        (*env)->ReleaseStringUTFChars(env, outputFile, output);
        return (jint)result;
    }
    x264_decoder_validate();
    // ffmpeg -i inputfile -vf "crop=w:h" -acodec copy outputfile
    for (i = 0; i < argc; i++) {
        argv[i] = (char*)malloc(256);
        if (NULL == argv[i]) {
            break;
        }
        switch (i) {
            case 0:
                snprintf(argv[i], 256, "%s", "wanpainative");
                break;
            case 1:
                snprintf(argv[i], 256, "%s", "-i");
                break;
            case 2:
                snprintf(argv[i], 256, "%s", input);
                break;
            case 3:
                snprintf(argv[i], 256, "%s", "-r");
                break;
            case 4:
                snprintf(argv[i], 256, "%s", "25");
                break;
            case 5:
                snprintf(argv[i], 256, "%s", "-vf");
                break;
            case 6:
                if (width > sw || height > sh) {
                    snprintf(argv[i], 256,
		        	"crop=%d:%d:%d:0,scale=%d:%d,transpose=%d",
			       	width, height, cropPos, sw, sh, transpose);
                } else {
                    snprintf(argv[i], 256,
			       	"crop=%d:%d:%d:0,transpose=%d",
			       	width, height, cropPos, transpose);
                }
                break;
           case 7:
                snprintf(argv[i], 256, "%s", "-acodec");
                break;
           case 8:
                snprintf(argv[i], 256, "%s", "copy");
                break;
           case 9:
                snprintf(argv[i], 256, "%s", "-vcodec");
                break;
           case 10:
                snprintf(argv[i], 256, "%s", "libx264");
                break;
           case 11:
                snprintf(argv[i], 256, "%s", output);
                break;
           default:
                break;
        };
    }
    (*env)->ReleaseStringUTFChars(env, inputFile, input);
    (*env)->ReleaseStringUTFChars(env, outputFile, output);
 
    if (i == argc) {
        result = process(argc, argv);
    }
    for (i = 0; i < argc; i++) {
        if (NULL != argv[i]) {
            free(argv[i]);
            argv[i] = NULL;
        }
    };
    free(argv);
    argv = NULL;
    return (jint)result;
}

/*
 * Class:     com_avos_minute_util_VideoEngine
 * Method:    scale
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_avos_minute_util_VideoEngine_crop2
  (JNIEnv *env, jobject obj, jstring inputFile, jstring outputFile,
   jint width, jint height, jint crop)
{
    jbyte *input = (*env)->GetStringUTFChars(env, inputFile, NULL);
    jbyte *output = (*env)->GetStringUTFChars(env, outputFile, NULL);
    int i = 0;
    int result = -1;
    int argc = 10;
    char** argv = (char**)malloc(sizeof(char*) * argc);
    if (NULL == argv) {
        (*env)->ReleaseStringUTFChars(env, inputFile, input);
        (*env)->ReleaseStringUTFChars(env, outputFile, output);
        return (jint)result;
    }
    x264_decoder_validate();
    // ffmpeg -i inputfile -vf "crop=w:h" -acodec copy outputfile
    for (i = 0; i < argc; i++) {
        argv[i] = (char*)malloc(256);
        if (NULL == argv[i]) {
            break;
        }
        switch (i) {
            case 0:
                snprintf(argv[i], 256, "%s", "wanpainative");
                break;
            case 1:
                snprintf(argv[i], 256, "%s", "-i");
                break;
            case 2:
                snprintf(argv[i], 256, "%s", input);
                break;
            case 3:
                snprintf(argv[i], 256, "%s", "-vf");
                break;
            case 4:
                snprintf(argv[i], 256, "scale=%d:%d", width, height);
		break;
           case 5:
                snprintf(argv[i], 256, "%s", "-acodec");
                break;
           case 6:
                snprintf(argv[i], 256, "%s", "copy");
                break;
           case 7:
                snprintf(argv[i], 256, "%s", "-vcodec");
                break;
           case 8:
                snprintf(argv[i], 256, "%s", "libx264");
                break;
           case 9:
                snprintf(argv[i], 256, "%s", output);
                break;
           default:
                break;
        };
    }
    (*env)->ReleaseStringUTFChars(env, inputFile, input);
    (*env)->ReleaseStringUTFChars(env, outputFile, output);
 
    if (i == argc) {
        result = process(argc, argv);
    }
    for (i = 0; i < argc; i++) {
        if (NULL != argv[i]) {
            free(argv[i]);
            argv[i] = NULL;
        }
    };
    free(argv);
    argv = NULL;
    return (jint)result;
}

JNIEXPORT jint JNICALL Java_com_avos_minute_util_VideoEngine_crop7
  (JNIEnv *env, jobject obj, jstring inputFile, jstring outputFile,
   jstring wmFile)
{
    jbyte *input = (*env)->GetStringUTFChars(env, inputFile, NULL);
    jbyte *output = (*env)->GetStringUTFChars(env, outputFile, NULL);
    jbyte *wmpath = (*env)->GetStringUTFChars(env, wmFile, NULL);
    int i = 0;
    int result = -1;
    int argc = 10;
    char** argv = (char**)malloc(sizeof(char*) * argc);
    if (NULL == argv) {
        (*env)->ReleaseStringUTFChars(env, inputFile, input);
        (*env)->ReleaseStringUTFChars(env, outputFile, output);
        (*env)->ReleaseStringUTFChars(env, wmFile, wmpath);
        return (jint)result;
    }
    x264_decoder_validate();
    for (i = 0; i < argc; i++) {
        argv[i] = (char*)malloc(256);
        if (NULL == argv[i]) {
            break;
        }
        switch (i) {
            case 0:
                snprintf(argv[i], 256, "%s", "wanpainative");
                break;
            case 1:
                snprintf(argv[i], 256, "%s", "-i");
                break;
            case 2:
                snprintf(argv[i], 256, "%s", input);
                break;
            case 3:
                snprintf(argv[i], 256, "%s", "-vf");
                break;
            case 4:
                snprintf(argv[i], 256, "%s", wmpath);
                break;
            case 5:
                snprintf(argv[i], 256, "%s", "-acodec");
                break;
            case 6:
                snprintf(argv[i], 256, "%s", "copy");
                break;
            case 7:
                snprintf(argv[i], 256, "%s", "-vcodec");
                break;
            case 8:
                snprintf(argv[i], 256, "%s", "libx264");
                break;
            case 9:
                snprintf(argv[i], 256, "%s", output);
                break;
            default:
                break;
        };
    }
    (*env)->ReleaseStringUTFChars(env, inputFile, input);
    (*env)->ReleaseStringUTFChars(env, outputFile, output);
    (*env)->ReleaseStringUTFChars(env, wmFile, wmpath);
 
    if (i == argc) {
        result = process(argc, argv);
    }
    for (i = 0; i < argc; i++) {
        if (NULL != argv[i]) {
            free(argv[i]);
            argv[i] = NULL;
        }
    };
    free(argv);
    argv = NULL;
    return (jint)result;
}

