/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_avos_minute_util_VideoEngine */

#ifndef _Included_com_avos_minute_util_VideoEngine
#define _Included_com_avos_minute_util_VideoEngine
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *jvm, void* reserved);

/*
 * Class:     com_avos_minute_util_VideoEngine
 * Method:    crop
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_avos_minute_util_VideoEngine_crop
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint, jint);

JNIEXPORT jint JNICALL Java_com_avos_minute_util_VideoEngine_crop1
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint, jint);

/*
 * Class:     com_avos_minute_util_VideoEngine
 * Method:    crop
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_avos_minute_util_VideoEngine_crop3(
  JNIEnv *, jobject, jstring, jstring, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_avos_minute_util_VideoEngine
 * Method:    crop
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_avos_minute_util_VideoEngine_crop2
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint);


/*
 * Class:     com_avos_minute_util_VideoEngine
 * Method:    demux
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_avos_minute_util_VideoEngine_crop4
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_avos_minute_util_VideoEngine
 * Method:    decodeFrames
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_avos_minute_util_VideoEngine_crop5 (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_avos_minute_util_VideoEngine
 * Method:    encodeFrames
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_avos_minute_util_VideoEngine_crop6 (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_avos_minute_util_VideoEngine
 * Method:    encodeFrames
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_avos_minute_util_VideoEngine_crop7 (JNIEnv *, jobject, jstring, jstring, jstring);


#ifdef __cplusplus
}
#endif
#endif
